version: '3.8'

networks:
  titan_network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: titan_desert_backend
    volumes:
      - ./titanDB/data:/data
    ports:
      - "8000:8000"
    environment:
      - SQLITE_DB_PATH=/data/titan_desert_solidario.db
    networks:
      - titan_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: titan_desert_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8000/api/v1
    networks:
      - titan_network
